# Generated by Django 5.0.4 on 2024-04-07 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_cart_is_active_cart_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.AddField(
            model_name='user',
            name='img',
            field=models.ImageField(default='avatar/default.png', upload_to='avatar/'),
        ),
    ]
