# Generated by Django 5.0.4 on 2024-04-07 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_user_avatar_user_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='img',
            new_name='avatar',
        ),
    ]
